### ISSUE TITLE
can not run up

### ISSUE THREAD

**Issue by brainee** [hydro-sdk/hydro_demo#122]
> node node_modules/@hydro-sdk/hydro-sdk/dist/compiler -t ota/hello-world.ts -m hello-world -d assets -p debug

Build d9a053b259311d6139ba1bac901853eecc21ffe77544d4222082ddbf70bb3550
Compiling  [████████████████████████████████████████] 202/202 ota/hello-world.ts
Finished build in 30412ms
ota/hello-world.ts ----> assets/hello-world.hc
ota/hello-world.ts ----> assets/hello-world.hc.sha256
ota/hello-world.ts ----> assets/hello-world.hc.symbols

flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60128
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60128
flutter: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60129
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60129
flutter: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60150
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60150
flutter: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60152
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60152
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60152
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60152
flutter: I/Hydro 0 native, 562 virtual prototypes
flutter: I/Hydro 0 native, 562 virtual prototypes
flutter: Another exception was thrown: SocketException: OS Error: Connection refused, errno = 61, address = localhost, port = 60152

**Comment by chgibb** [comment]
Hi @brainee thanks for trying out Hydro! `RunFromNetwork` is looking for a local server to connect to to pull your code from. You'll need to use the `-w ota` switch to start that server and watch for changes in your code.

**Comment by brainee** [comment]
thanks, i have ran up the demo,it's good work.

**Comment by brainee** [comment]
i want to convert  a whole project, do you have any idea?

**Comment by chgibb** [comment]
There's no tooling to convert existing Flutter apps, no. I also don't recommend using Hydro in production. It is still very much pre alpha in quality.

**Comment by StasKalishenko** [comment]
Is it possible to run from local file system (not using local web server with "-w ota" flags)?

**Comment by StasKalishenko** [comment]
And how to bind a custom widget? I'm trying to do it like in example (https://github.com/chgibb/hydro-sdk/blob/master/test/widget/customWidget-1_test.dart https://github.com/chgibb/hydro-sdk/blob/master/test/widget/customWidget-1.ts) and getting "attempt to index a nil value null myCustomWidget".

MyCustomWidget I put in main.dart:
`class MyCustomWidget extends StatelessWidget {
  final Key key;
  final Color color;
  final Widget text;
  final MainAxisAlignment mainAxisAlignment;

  MyCustomWidget({
    @required this.key,
    @required this.color,
    @required this.text,
    @required this.mainAxisAlignment,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
        key: key,
        color: color,
        child: Row(
          mainAxisAlignment: mainAxisAlignment,
          children: [text],
        ));
  }
}`

myCustomWidget.ts (put it in /ota):
`import { Color } from "@hydro-sdk/hydro-sdk/runtime/dart/ui/color";
import { Key } from "@hydro-sdk/hydro-sdk/runtime/flutter/foundation/key";
import { Icon } from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/icon";
import { MainAxisAlignment } from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/mainAxisAlignment";
import { StatelessWidget } from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/statelessWidget";
import { Text } from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/text";
import { CupertinoColors } from "@hydro-sdk/hydro-sdk/runtime/flutter/cupertino/cupertinoColors";
import { CupertinoIcons } from "@hydro-sdk/hydro-sdk/runtime/flutter/cupertino/cupertinoIcons";
import { MaterialApp } from "@hydro-sdk/hydro-sdk/runtime/flutter/material/materialApp";
import { TextStyle } from "@hydro-sdk/hydro-sdk/runtime/flutter/painting/textStyle";
import { runApp } from "@hydro-sdk/hydro-sdk/runtime/flutter/runApp";

export interface MyCustomWidgetProps {
    key: Key;
    color: Color;
    text: Text;
    mainAxisAlignment: MainAxisAlignment;
}

declare const org: {
    myPackage: {
        myCustomWidget: (
            this: void,
            props: MyCustomWidgetProps
        ) => MyCustomWidget;
    };
};

export class MyCustomWidget extends StatelessWidget {
    private props: MyCustomWidgetProps;
    public constructor(props: MyCustomWidgetProps) {
        super();
        this.props = props;
    }

    public build() {
        return org.myPackage.myCustomWidget(this.props);
    }
}`

And modified hello-world.ts:
`import { runApp } from "@hydro-sdk/hydro-sdk/runtime/flutter/runApp";
//Make sure to import from /index specifically if using barell imports.
//The compiler won't resolve /index by itself
import {
    StatelessWidget,
    Text,
    Container,
    TextEditingController,
    Center
} from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/index";
import { MaterialApp, Scaffold } from "@hydro-sdk/hydro-sdk/runtime/flutter/material/index";
import { Widget } from "@hydro-sdk/hydro-sdk/runtime/flutter/widget";
import { Key } from "@hydro-sdk/hydro-sdk/runtime/flutter/foundation/key";

import { CupertinoColors } from "@hydro-sdk/hydro-sdk/runtime/flutter/cupertino/cupertinoColors";
import { MainAxisAlignment } from "@hydro-sdk/hydro-sdk/runtime/flutter/widgets/mainAxisAlignment";
import { MyCustomWidget } from "./myCustomWidget";

class MyWidget extends StatelessWidget {
    private controller = new TextEditingController({ text: "Some convoluted but familiar functions" });
    public constructor() {
        super();
    }

    public build(): Widget {
        console.log(this.controller.getText().toLowerCase());
        return new MaterialApp({
            home:
                new Scaffold({
                    body:
                        new Center({
                            child:
                                new MyCustomWidget({
									key: new Key("Key for MyCustomwidget"),
									color: CupertinoColors.activeBlue.color,
									text: new Text("MyCustomWidget"),
									mainAxisAlignment: MainAxisAlignment.center,
								}),
                        })
                })
        });
    }
}

runApp(() => new MyWidget());
`

Compiler shows that everything is fine. But when I run app, I'm getting "attempt to index a nil value null myCustomWidget" error message. What I'm doing wrong?

**Comment by chgibb** [comment]
@StasKalishenko for running code from the device, the only option at the moment is running from your apps asset bundle with `RunFromBundle` . With respect to custom widget binding, it looks like you're missing the namespace setup in your `RunFrom*`
